# This file is generated by the Geant4 CMake buildsystem and should not be editted
#
# This file stores paths and settings to external libraries found and used by this
# install of Geant4 when it was built.

macro(geant4_set_and_check_package_variable _name _value _type _docstring)
  if(DEFINED ${_name})
    if(NOT ("${${_name}}" STREQUAL "${_value}"))
      message(WARNING "Value of '${_name}' is already set and does not match value set at Geant4 build-time")
    endif()
  else()
    set(${_name} ${_value} CACHE ${_type} "${_docstring}")
  endif()
endmacro()


# EXPAT Build Time Settings
geant4_set_and_check_package_variable(EXPAT_INCLUDE_DIR "/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/usr/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(EXPAT_LIBRARY "/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/usr/lib/libexpat.tbd" FILEPATH "Path to a library.")

# TBB Build Time Settings

# Freetype Build Time Settings
geant4_set_and_check_package_variable(FREETYPE_INCLUDE_DIR_freetype2 "/opt/homebrew/include/freetype2" PATH "Path to a file.")
geant4_set_and_check_package_variable(FREETYPE_INCLUDE_DIR_ft2build "/opt/homebrew/include/freetype2" PATH "Path to a file.")
geant4_set_and_check_package_variable(FREETYPE_LIBRARY_RELEASE "/opt/homebrew/lib/libfreetype.dylib" FILEPATH "Path to a library.")

# OpenGL Build Time Settings
geant4_set_and_check_package_variable(OPENGL_INCLUDE_DIR "/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/OpenGL.framework" PATH "Include for OpenGL on OS X")
geant4_set_and_check_package_variable(OPENGL_gl_LIBRARY "/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/System/Library/Frameworks/OpenGL.framework" FILEPATH "OpenGL library for OS X")

# XQuartzGL Build Time Settings
geant4_set_and_check_package_variable(XQuartzGL_INCLUDE_DIR "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(XQuartzGL_gl_LIBRARY "/usr/X11R6/lib/libGL.dylib" FILEPATH "Path to a library.")

# X11 Build Time Settings
geant4_set_and_check_package_variable(X11_X11_INCLUDE_PATH "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(X11_X11_LIB "/usr/X11R6/lib/libX11.dylib" FILEPATH "Path to a library.")
geant4_set_and_check_package_variable(X11_ICE_INCLUDE_PATH "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(X11_ICE_LIB "/usr/X11R6/lib/libICE.dylib" FILEPATH "Path to a library.")
geant4_set_and_check_package_variable(X11_SM_INCLUDE_PATH "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(X11_SM_LIB "/usr/X11R6/lib/libSM.dylib" FILEPATH "Path to a library.")
geant4_set_and_check_package_variable(X11_Xext_INCLUDE_PATH "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(X11_Xext_LIB "/usr/X11R6/lib/libXext.dylib" FILEPATH "Path to a library.")
geant4_set_and_check_package_variable(X11_Xmu_INCLUDE_PATH "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(X11_Xmu_LIB "/usr/X11R6/lib/libXmu.dylib" FILEPATH "Path to a library.")
geant4_set_and_check_package_variable(X11_Xt_INCLUDE_PATH "/usr/X11R6/include" PATH "Path to a file.")
geant4_set_and_check_package_variable(X11_Xt_LIB "/usr/X11R6/lib/libXt.dylib" FILEPATH "Path to a library.")
